In [8]:
import pandas
import json
from pprint import pprint
from connect_sql_db import build_engine

In [9]:
engine = build_engine(database_name="database1",host="35.225.193.21")

In [10]:
dataset = []
for line in open("../../../data/yelp_dataset/yelp_academic_dataset_business.json"):
    dataset.append(json.loads(line))

In [11]:
len(dataset)

209393

In [12]:
for i in dataset[0:1]:
    pprint(list(i.keys()))

['business_id',
 'name',
 'address',
 'city',
 'state',
 'postal_code',
 'latitude',
 'longitude',
 'stars',
 'review_count',
 'is_open',
 'attributes',
 'categories',
 'hours']

In [13]:

categories = {}
categories_lst = []

for i in dataset:
    if i != None:
        if i["business_id"] != None and i["categories"] != None and "Restaurants" in i["categories"].split(","):
            categories[f'{i["business_id"]},{i["name"]}'] = i["categories"]
            for x in i["categories"].split(","):
                categories_lst.append(x.strip())

In [15]:
# [
#     "Adult Education",
#     "Amateur Sports Teams",
#     "Acupuncture",
#     "Advertising",
#     "Airport Lounges",
#     "",
#     "",
#     ""
# ]
def search_categories():
    y = input()
    for i,v in categories.items():
        for x in v.split(","):
            if y == x.strip():
                z = i.split(",")
                print(z[0],"\n",z[1],"\n", v,"\n")


#search_categories()

In [16]:
new_dict = dict(zip(categories_lst,[0 for i in range(len(categories_lst))]))

for i in categories_lst:
    if i in new_dict.keys():
        new_dict[i] += 1

set(categories_lst)

{'Acai Bowls',
 'Active Life',
 'Acupuncture',
 'Adult Education',
 'Adult Entertainment',
 'Advertising',
 'Afghan',
 'African',
 'Airport Lounges',
 'Airports',
 'Amateur Sports Teams',
 'American (New)',
 'American (Traditional)',
 'Amusement Parks',
 'Animal Shelters',
 'Antiques',
 'Appliances',
 'Appliances & Repair',
 'Arabian',
 'Arcades',
 'Argentine',
 'Armenian',
 'Art Classes',
 'Art Galleries',
 'Art Schools',
 'Art Supplies',
 'Arts & Crafts',
 'Arts & Entertainment',
 'Asian Fusion',
 'Australian',
 'Austrian',
 'Auto Glass Services',
 'Auto Parts & Supplies',
 'Auto Repair',
 'Automotive',
 'Bagels',
 'Bakeries',
 'Bangladeshi',
 'Banks & Credit Unions',
 'Bar Crawl',
 'Barbeque',
 'Barbers',
 'Bars',
 'Basque',
 'Beauty & Spas',
 'Bed & Breakfast',
 'Beer',
 'Beer Bar',
 'Beer Gardens',
 'Belgian',
 'Beverage Store',
 'Bistros',
 'Boat Dealers',
 'Boat Repair',
 'Bocce Ball',
 'Body Shops',
 'Books',
 'Bookstores',
 'Bowling',
 'Brasseries',
 'Brazilian',
 'Breakfast & Brunch',
 'Breweries',
 'Brewpubs',
 'British',
 'Bubble Tea',
 'Buffets',
 'Building Supplies',
 'Burgers',
 'Burmese',
 'Butcher',
 'Cabaret',
 'Cafes',
 'Cafeteria',
 'Cajun/Creole',
 'Cambodian',
 'Campgrounds',
 'Canadian (New)',
 'Candy Stores',
 'Cannabis Clinics',
 'Cantonese',
 'Car Dealers',
 'Car Rental',
 'Car Wash',
 'Cards & Stationery',
 'Caribbean',
 'Casinos',
 'Catalan',
 'Caterers',
 'Check Cashing/Pay-day Loans',
 'Cheese Shops',
 'Cheesesteaks',
 'Chicken Shop',
 'Chicken Wings',
 'Chinese',
 'Chiropractors',
 'Chocolatiers & Shops',
 'Churches',
 'Cinema',
 'Cocktail Bars',
 'Coffee & Tea',
 'Coffee & Tea Supplies',
 'Coffee Roasteries',
 'Colleges & Universities',
 'Colombian',
 'Comedy Clubs',
 'Comfort Food',
 'Comic Books',
 'Commercial Truck Repair',
 'Community Centers',
 'Community Service/Non-Profit',
 'Contractors',
 'Convenience Stores',
 'Conveyor Belt Sushi',
 'Cooking Classes',
 'Cooking Schools',
 'Cosmetics & Beauty Supply',
 'Country Clubs',
 'Country Dance Halls',
 'Couriers & Delivery Services',
 'Creperies',
 'Cuban',
 'Cupcakes',
 'Currency Exchange',
 'Custom Cakes',
 'Czech',
 'Dance Clubs',
 'Day Spas',
 'Delicatessen',
 'Delis',
 'Department Stores',
 'Desserts',
 'Diagnostic Services',
 'Dim Sum',
 'Diners',
 'Dinner Theater',
 'Discount Store',
 'Distilleries',
 'Dive Bars',
 'Do-It-Yourself Food',
 'Doctors',
 'Dominican',
 'Donairs',
 'Donuts',
 'Drugstores',
 'Dry Cleaning & Laundry',
 'Dumplings',
 'Education',
 'Egyptian',
 'Electricians',
 'Empanadas',
 'Eritrean',
 'Escape Games',
 'Estate Liquidation',
 'Ethical Grocery',
 'Ethiopian',
 'Ethnic Food',
 'Ethnic Grocery',
 'Event Planning & Services',
 'Eyebrow Services',
 'Eyelash Service',
 'Falafel',
 'Farmers Market',
 'Fashion',
 'Fast Food',
 'Festivals',
 'Filipino',
 'Financial Services',
 'Fish & Chips',
 'Fitness & Instruction',
 'Flea Markets',
 'Flooring',
 'Florists',
 'Flowers & Gifts',
 'Fondue',
 'Food',
 'Food Court',
 'Food Delivery Services',
 'Food Stands',
 'Food Tours',
 'Food Trucks',
 'Foundation Repair',
 'French',
 'Fruits & Veggies',
 'Furniture Stores',
 'Gas Stations',
 'Gastropubs',
 'Gay Bars',
 'Gelato',
 'German',
 'Gift Shops',
 'Gluten-Free',
 'Golf',
 'Golf Lessons',
 'Greek',
 'Grilling Equipment',
 'Grocery',
 'Guamanian',
 'Guest Houses',
 'Gyms',
 'Hainan',
 'Hair Loss Centers',
 'Hair Removal',
 'Hair Salons',
 'Hair Stylists',
 'Haitian',
 'Hakka',
 'Halal',
 'Handyman',
 'Hardware Stores',
 'Hawaiian',
 'Health & Medical',
 'Health Markets',
 'Heating & Air Conditioning/HVAC',
 'Herbs & Spices',
 'Himalayan/Nepalese',
 'Historical Tours',
 'Hobby Shops',
 'Home & Garden',
 'Home Decor',
 'Home Services',
 'Hong Kong Style Cafe',
 'Hookah Bars',
 'Horse Racing',
 'Hospitals',
 'Hot Dogs',
 'Hot Pot',
 'Hotel bar',
 'Hotels',
 'Hotels & Travel',
 'Hungarian',
 'Iberian',
 'Ice Cream & Frozen Yogurt',
 'Imported Food',
 'Indian',
 'Indonesian',
 'Indoor Playcentre',
 'Interior Design',
 'International',
 'International Grocery',
 'Internet Cafes',
 'Irish',
 'Irish Pub',
 'Italian',
 'Izakaya',
 'Japanese',
 'Japanese Curry',
 'Jazz & Blues',
 'Jewelry',
 'Juice Bars & Smoothies',
 'Junk Removal & Hauling',
 'Karaoke',
 'Kebab',
 'Kids Activities',
 'Kitchen & Bath',
 'Kitchen Supplies',
 'Knife Sharpening',
 'Korean',
 'Kosher',
 'Laboratory Testing',
 'Lakes',
 'Laotian',
 'Latin American',
 'Laundry Services',
 'Lebanese',
 'Libraries',
 'Lighting Fixtures & Equipment',
 'Live/Raw Food',
 'Local Flavor',
 'Local Services',
 'Lounges',
 'Macarons',
 'Mags',
 'Malaysian',
 'Marinas',
 'Masonry/Concrete',
 'Massage',
 'Massage Therapy',
 'Mattresses',
 'Meat Shops',
 'Medical Cannabis Referrals',
 'Medical Centers',
 'Medical Spas',
 'Mediterranean',
 'Mexican',
 'Middle Eastern',
 'Mobile Phones',
 'Modern European',
 'Mongolian',
 'Moroccan',
 'Music & DVDs',
 'Music & Video',
 'Music Venues',
 'Musicians',
 'Nail Salons',
 'Nail Technicians',
 'Naturopathic/Holistic',
 'New Mexican Cuisine',
 'Nightlife',
 'Noodles',
 'Nutritionists',
 'Office Equipment',
 'Olive Oil',
 'Organic Stores',
 'Outdoor Furniture Stores',
 'Outlet Stores',
 'Pain Management',
 'Paint & Sip',
 'Paint-Your-Own Pottery',
 'Pakistani',
 'Pan Asian',
 'Pancakes',
 'Parks',
 'Party & Event Planning',
 'Party Equipment Rentals',
 'Party Supplies',
 'Pasta Shops',
 'Patisserie/Cake Shop',
 'Performing Arts',
 'Persian/Iranian',
 'Personal Chefs',
 'Peruvian',
 'Pet Adoption',
 'Pet Services',
 'Pets',
 'Pharmacy',
 'Photography Stores & Services',
 'Physical Therapy',
 'Piano Bars',
 'Pita',
 'Pizza',
 'Poke',
 'Police Departments',
 'Polish',
 'Polynesian',
 'Pool Halls',
 'Pop-Up Restaurants',
 'Portuguese',
 'Poutineries',
 'Pretzels',
 'Professional Services',
 'Pub Food',
 'Public Markets',
 'Public Services & Government',
 'Public Transportation',
 'Pubs',
 'Puerto Rican',
 'Race Tracks',
 'Ramen',
 'Real Estate',
 'Real Estate Services',
 'Reflexology',
 'Religious Organizations',
 'Resorts',
 'Restaurant Supplies',
 'Restaurants',
 'Russian',
 'Salad',
 'Salvadoran',
 'Sandwiches',
 'Scandinavian',
 'Seafood',
 'Seafood Markets',
 'Senegalese',
 'Shanghainese',
 'Shared Office Spaces',
 'Shaved Ice',
 'Shaved Snow',
 'Shopping',
 'Shopping Centers',
 'Sicilian',
 'Singaporean',
 'Skin Care',
 'Skydiving',
 'Slovakian',
 'Smokehouse',
 'Soba',
 'Social Clubs',
 'Soul Food',
 'Soup',
 'South African',
 'Southern',
 'Spanish',
 'Speakeasies',
 'Specialty Food',
 'Specialty Schools',
 'Sporting Goods',
 'Sports Bars',
 'Sri Lankan',
 'Stadiums & Arenas',
 'Steakhouses',
 'Street Vendors',
 'Strip Clubs',
 'Studio Taping',
 'Sugar Shacks',
 'Summer Camps',
 'Supper Clubs',
 'Sushi Bars',
 'Swimming Pools',
 'Swiss Food',
 'Synagogues',
 'Syrian',
 'Szechuan',
 'Tabletop Games',
 'Tacos',
 'Taiwanese',
 'Tapas Bars',
 'Tapas/Small Plates',
 'Tea Rooms',
 'Team Building Activities',
 'Teppanyaki',
 'Tex-Mex',
 'Thai',
 'Themed Cafes',
 'Thrift Stores',
 'Tiki Bars',
 'Tobacco Shops',
 'Tours',
 'Trainers',
 'Transportation',
 'Trinidadian',
 'Truck Rental',
 'Turkish',
 'Ukrainian',
 'Used',
 'Vegan',
 'Vegetarian',
 'Venezuelan',
 'Venues & Event Spaces',
 'Videos & Video Game Rental',
 'Vietnamese',
 'Vintage & Consignment',
 'Vinyl Records',
 'Vitamins & Supplements',
 'Waffles',
 'Walking Tours',
 'Waxing',
 'Web Design',
 'Wedding Planning',
 'Weight Loss Centers',
 'Whiskey Bars',
 'Wholesale Stores',
 'Wholesalers',
 'Wigs',
 'Wine & Spirits',
 'Wine Bars',
 'Wine Tasting Room',
 'Wine Tours',
 'Wineries',
 "Women's Clothing",
 'Wraps',
 'Yelp Events'}

In [17]:
data = {}
for key,value in new_dict.items():
    data[key] = [value]

In [18]:
business_categories_count = pandas.DataFrame(data, index = ["count"])

In [19]:
business_categories_count = business_categories_count.T
business_categories_count.head(10)

                count
Restaurants     19456
Cheesesteaks       58
Poutineries        59
Burgers          1653
Food             3258
Vietnamese        467
Soup              224
Lebanese           78
Middle Eastern    355
Fast Food        2493

In [20]:
 business_categories_count = business_categories_count.sort_values("count" , ascending = False).copy()

In [21]:
business_categories_count.loc[business_categories_count["count"] < 5].head(10)

                  count
Resorts               4
Pancakes              4
Sicilian              4
Home Decor            4
Wedding Planning      4
Dominican             4
Wigs                  4
Contractors           4
Burmese               4
Macarons              4

In [22]:
empty = []
for line in open("../../../data/yelp_dataset/yelp_academic_dataset_business.json","r"):
    empty.append(json.loads(line))

In [23]:
attributes_lst = []
for i in empty:
        if i["attributes"] != None:
            for attribute in i["attributes"].keys():
                attributes_lst.append(attribute)

In [24]:
set(attributes_lst)

{'AcceptsInsurance',
 'AgesAllowed',
 'Alcohol',
 'Ambience',
 'BYOB',
 'BYOBCorkage',
 'BestNights',
 'BikeParking',
 'BusinessAcceptsBitcoin',
 'BusinessAcceptsCreditCards',
 'BusinessParking',
 'ByAppointmentOnly',
 'Caters',
 'CoatCheck',
 'Corkage',
 'DietaryRestrictions',
 'DogsAllowed',
 'DriveThru',
 'GoodForDancing',
 'GoodForKids',
 'GoodForMeal',
 'HairSpecializesIn',
 'HappyHour',
 'HasTV',
 'Music',
 'NoiseLevel',
 'Open24Hours',
 'OutdoorSeating',
 'RestaurantsAttire',
 'RestaurantsCounterService',
 'RestaurantsDelivery',
 'RestaurantsGoodForGroups',
 'RestaurantsPriceRange2',
 'RestaurantsReservations',
 'RestaurantsTableService',
 'RestaurantsTakeOut',
 'Smoking',
 'WheelchairAccessible',
 'WiFi'}

In [25]:
business_categories_count.sort_values("count" , ascending = False).head(30)

                           count
Restaurants                19456
Food                        3258
Fast Food                   2493
Pizza                       2311
Sandwiches                  2050
Mexican                     1872
American (Traditional)      1713
Burgers                     1653
Chinese                     1653
Nightlife                   1645
Bars                        1561
Breakfast & Brunch          1476
Italian                     1398
American (New)              1148
Coffee & Tea                 897
Japanese                     879
Cafes                        818
Chicken Wings                724
Sushi Bars                   713
Seafood                      657
Salad                        644
Asian Fusion                 539
Barbeque                     535
Indian                       522
Event Planning & Services    521
Thai                         515
Mediterranean                494
Vietnamese                   467
Delis                        440
Canadian (New)               433

In [26]:
business_table = pandas.read_sql("select * from business_table", con = engine)

In [27]:
business_table.count()

business_id     20311
name            20311
address         20311
city            20311
state           20311
postal_code     20311
latitude        20311
longitude       20311
stars           20311
review_count    20311
is_open         20311
dtype: int64

In [28]:
len(set(business_table["business_id"].tolist()))

20311

In [30]:
len(set(business_table.business_id.tolist()))

20311

In [164]:
lst = []
business_ids = []
for i in dataset:
    if i != None and i["categories"] != None:
        if i["business_id"] != None and "Restaurants" in i["categories"].split(","):
            for x in i["categories"].split(","):
                if x.strip() in new_df_2.columns:
                    new_df_2.loc[new_df_2.business_id == i["business_id"],x.strip()] = 1

In [113]:

for i in dataset:
    if i != None and i["attributes"] != None:
        if i["business_id"] != None and i["categories"] != None and "Ambience" in i["attributes"].keys() != None and "Restaurants" in i["categories"].split(","):

            for v in i["attributes"]["Ambience"].replace("'","").replace("{","").replace("}","").split(","):
                try:
                    new_df.loc[new_df["business_id"] == i["business_id"], v.strip().split(":")[0]] = v.strip().split(":")[1]
                except IndexError:
                    new_df.loc[new_df["business_id"] == i["business_id"], v.strip().split(":")[0]] = "Index Error"

In [67]:
new_df = pandas.DataFrame({
    "business_id":business_ids,
    "ambience":ambience
})

In [100]:
check_me = list(set(columns))

In [101]:
check_me

['hipster',
 'classy',
 'intimate',
 'trendy',
 'casual',
 'touristy',
 'divey',
 'romantic',
 'upscale']

In [129]:
new_df.drop("ambience",axis = 1,inplace = True)

In [140]:
def replacer(x):
    if type(x) == int:
        return x
    if "False" in x or "None" in x:
        return 0
    elif "True" in x:
        return 1
    else:
        return x

for i in new_df.drop("business_id",axis = 1).columns:
    print(i)
    new_df[i] = new_df[i].apply(lambda x: replacer(x))

hipster
classy
intimate
trendy
casual
touristy
divey
romantic
upscale

In [142]:
for i in new_df.drop("business_id",axis = 1).columns:
    print(new_df[i].value_counts())

0    14868
1      251
Name: hipster, dtype: int64
0    13494
1     1625
Name: classy, dtype: int64
0    14938
1      181
Name: intimate, dtype: int64
0    14510
1      609
Name: trendy, dtype: int64
0    9116
1    6003
Name: casual, dtype: int64
0    15046
1       73
Name: touristy, dtype: int64
0    14895
1      224
Name: divey, dtype: int64
0    14937
1      182
Name: romantic, dtype: int64
0    14970
1      149
Name: upscale, dtype: int64

In [143]:
attributes_table = pandas.read_sql("select * from attributes_table",con=engine)

In [178]:
new_df.duplicated().sum()

0

In [154]:
new_attributes_table = pandas.merge(attributes_table, new_df, how="inner",on="business_id")

In [155]:
new_attributes_table

,business_id,name,byob,bikeparking,businessacceptsbitcoin,businessacceptscreditcards,byappointmentonly,caters,coatcheck,corkage,...,wifi_paid,hipster,classy,intimate,trendy,casual,touristy,divey,romantic,upscale
0,rVBPQdeayMYht4Uv_FOLHg,Gourmet Burger Company,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,98hyK2QEUeI8v2y0AghfZA,Pho Lee's Vietnamese Restaurant,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,LoRef3ChgZKbxUio-sHgQg,Amir,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,tLpkSwdtqqoXwU0JAGnApw,Wendy's,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,ZkzutF0P_u0C0yTulwaHkA,Lelulos Pizzeria,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15114,ZM-BSBJRa5Wv8iYtLpEcww,Resto-Cafe Oxford,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
15115,7V82ANZ7_ARkA7o0pAMAlA,Galaxy Cafe,0,1,0,1,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
15116,8dK-8e006F_it5bNxTVlaQ,Famous Dave's Bar-B-Que,0,0,0,1,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
15117,GAgEoHcf4PSuZRS5Zd3ltA,Q's Shawarma,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15118,hskVqZCPqy-omm9CHi44xQ,Domino's,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [162]:
new_df_2 = pandas.DataFrame({
    "business_id":business_ids
})

for i in list(set(lst)):
    new_df_2[i] = 0

dZluiJ9AYgW0UtzShwBtgQ    18
QiapXu38GZwFZQ8X0hopIw    18
sZIVzaaEBp_HiYutZ2lWag    17
kHVXISoSMdgKySGiUVhhtw    15
I3Saf0s5ybDKprYPPNWqtA    14
                          ..
2eL6ete3g0EtVpuRx2sF9w     1
AtOE7tSrJn1HXnU9YoUbPQ     1
iJ818L_78MFGOZs6hUVW4A     1
9tK5ibv58TxxpndehLXjDg     1
ph3zzf0n3h1CnZMQoOYr5g     1
Name: business_id, Length: 19456, dtype: int64
0    67953
1       13
Name: Guamanian, dtype: int64
0    67938
1       28
Name: Bangladeshi, dtype: int64
0    67951
1       15
Name: Walking Tours, dtype: int64
0    67940
1       26
Name: Resorts, dtype: int64
0    67409
1      557
Name: Beer Bar, dtype: int64
0    67955
1       11
Name: Cooking Classes, dtype: int64
0    67779
1      187
Name: Casinos, dtype: int64
0    67944
1       22
Name: Department Stores, dtype: int64
0    67955
1       11
Name: Medical Centers, dtype: int64
0    66372
1     1594
Name: Thai, dtype: int64
0    67927
1       39
Name: Pretzels, dtype: int64
0    67955
1       11
Name: Studio Taping, dtype: int64
0    67625
1      341
Name: Food Stands, dtype: int64
0    67838
1      128
Name: Salvadoran, dtype: int64
0    67961
1        5
Name: Auto Parts & Supplies, dtype: int64
0    67854
1      112
Name: Cuban, dtype: int64
0    67596
1      370
Name: Donuts, dtype: int64
0    67957
1        9
Name: Sugar Shacks, dtype: int64
0    67957
1        9
Name: Heating & Air Conditioning/HVAC, dtype: int64
0    66257
1     1709
Name: Diners, dtype: int64
0    67963
1        3
Name: Eritrean, dtype: int64
0    67956
1       10
Name: Armenian, dtype: int64
0    67910
1       56
Name: Indoor Playcentre, dtype: int64
0    67925
1       41
Name: Custom Cakes, dtype: int64
0    64275
1     3691
Name: Salad, dtype: int64
0    67946
1       20
Name: Laotian, dtype: int64
0    65663
1     2303
Name: Specialty Food, dtype: int64
0    67961
1        5
Name: Laboratory Testing, dtype: int64
0    67959
1        7
Name: Physical Therapy, dtype: int64
0    67958
1        8
Name: Knife Sharpening, dtype: int64
0    67803
1      163
Name: Irish, dtype: int64
0    67913
1       53
Name: Kids Activities, dtype: int64
0    67958
1        8
Name: Masonry/Concrete, dtype: int64
0    67956
1       10
Name: Campgrounds, dtype: int64
0    62713
1     5253
Name: Italian, dtype: int64
0    67962
1        4
Name: Thrift Stores, dtype: int64
0    67740
1      226
Name: Persian/Iranian, dtype: int64
0    67828
1      138
Name: Beauty & Spas, dtype: int64
0    67825
1      141
Name: Szechuan, dtype: int64
0    67959
1        7
Name: Empanadas, dtype: int64
0    67954
1       12
Name: Nutritionists, dtype: int64
0    64174
1     3792
Name: Cafes, dtype: int64
0    67934
1       32
Name: Cinema, dtype: int64
0    67940
1       26
Name: Dominican, dtype: int64
0    66588
1     1378
Name: Vietnamese, dtype: int64
0    67963
1        3
Name: Senegalese, dtype: int64
0    67797
1      169
Name: Turkish, dtype: int64
0    66016
1     1950
Name: Tacos, dtype: int64
0    67947
1       19
Name: Dry Cleaning & Laundry, dtype: int64
0    67070
1      896
Name: Chicken Shop, dtype: int64
0    65954
1     2012
Name: Canadian (New), dtype: int64
0    67962
1        4
Name: Australian, dtype: int64
0    67942
1       24
Name: Swimming Pools, dtype: int64
0    67854
1      112
Name: Golf, dtype: int64
0    67895
1       71
Name: Live/Raw Food, dtype: int64
0    67954
1       12
Name: Trainers, dtype: int64
0    67917
1       49
Name: Farmers Market, dtype: int64
0    67864
1      102
Name: Belgian, dtype: int64
0    67950
1       16
Name: Cosmetics & Beauty Supply, dtype: int64
0    66282
1     1684
Name: Indian, dtype: int64
0    67935
1       31
Name: Basque, dtype: int64
0    67957
1        9
Name: Eyelash Service, dtype: int64
0    67903
1       63
Name: Moroccan, dtype: int64
0    67353
1      613
Name: Southern, dtype: int64
0    67884
1       82
Name: International Grocery, dtype: int64
0    67848
1      118
Name: Pan Asian, dtype: int64
0    67331
1      635
Name: Tapas/Small Plates, dtype: int64
0    65896
1     2070
Name: Desserts, dtype: int64
0    67880
1       86
Name: Irish Pub, dtype: int64
0    67636
1      330
Name: Local Flavor, dtype: int64
0    67958
1        8
Name: Medical Spas, dtype: int64
0    67955
1       11
Name: Naturopathic/Holistic, dtype: int64
0    67921
1       45
Name: Sri Lankan, dtype: int64
0    67923
1       43
Name: Fashion, dtype: int64
0    67897
1       69
Name: International, dtype: int64
0    66964
1     1002
Name: Comfort Food, dtype: int64
0    67948
1       18
Name: Churches, dtype: int64
0    67954
1       12
Name: Interior Design, dtype: int64
1    67966
Name: Restaurants, dtype: int64
0    67949
1       17
Name: Hobby Shops, dtype: int64
0    67617
1      349
Name: Ramen, dtype: int64
0    67955
1       11
Name: Paint-Your-Own Pottery, dtype: int64
0    67962
1        4
Name: Hair Loss Centers, dtype: int64
0    60169
1     7797
Name: Pizza, dtype: int64
0    67943
1       23
Name: Skin Care, dtype: int64
0    67958
1        8
Name: Skydiving, dtype: int64
0    67912
1       54
Name: Hong Kong Style Cafe, dtype: int64
0    67959
1        7
Name: Polynesian, dtype: int64
0    67928
1       38
Name: Izakaya, dtype: int64
0    67649
1      317
Name: Imported Food, dtype: int64
0    67931
1       35
Name: Pancakes, dtype: int64
0    66746
1     1220
Name: Arts & Entertainment, dtype: int64
0    67577
1      389
Name: Bagels, dtype: int64
0    67960
1        6
Name: Estate Liquidation, dtype: int64
0    67762
1      204
Name: Poke, dtype: int64
0    67590
1      376
Name: Fish & Chips, dtype: int64
0    67959
1        7
Name: Tiki Bars, dtype: int64
0    67958
1        8
Name: Hair Stylists, dtype: int64
0    67957
1        9
Name: Pharmacy, dtype: int64
0    67957
1        9
Name: Hainan, dtype: int64
0    67931
1       35
Name: Whiskey Bars, dtype: int64
0    67959
1        7
Name: Car Wash, dtype: int64
0    67837
1      129
Name: Peruvian, dtype: int64
0    67812
1      154
Name: Waffles, dtype: int64
0    67900
1       66
Name: Books, dtype: int64
0    67960
1        6
Name: Boat Repair, dtype: int64
0    67781
1      185
Name: Cantonese, dtype: int64
0    67824
1      142
Name: Falafel, dtype: int64
0    59698
1     8268
Name: American (Traditional), dtype: int64
0    58876
1     9090
Name: Sandwiches, dtype: int64
0    66735
1     1231
Name: French, dtype: int64
0    67692
1      274
Name: Modern European, dtype: int64
0    67953
1       13
Name: Scandinavian, dtype: int64
0    67956
1       10
Name: Weight Loss Centers, dtype: int64
0    67934
1       32
Name: Teppanyaki, dtype: int64
0    60346
1     7620
Name: Burgers, dtype: int64
0    67961
1        5
Name: Airport Lounges, dtype: int64
0    67575
1      391
Name: Dim Sum, dtype: int64
0    66493
1     1473
Name: Beer, dtype: int64
0    67616
1      350
Name: Active Life, dtype: int64
0    67943
1       23
Name: Waxing, dtype: int64
0    67949
1       17
Name: Party Supplies, dtype: int64
0    67816
1      150
Name: Brasseries, dtype: int64
0    67960
1        6
Name: Mattresses, dtype: int64
0    67949
1       17
Name: Shared Office Spaces, dtype: int64
0    67955
1       11
Name: Community Centers, dtype: int64
0    67918
1       48
Name: Restaurant Supplies, dtype: int64
0    67675
1      291
Name: Creperies, dtype: int64
0    67960
1        6
Name: Speakeasies, dtype: int64
0    67918
1       48
Name: Cheese Shops, dtype: int64
0    67950
1       16
Name: Airports, dtype: int64
0    67929
1       37
Name: Egyptian, dtype: int64
0    67939
1       27
Name: Religious Organizations, dtype: int64
0    67943
1       23
Name: Hair Removal, dtype: int64
0    67762
1      204
Name: Tea Rooms, dtype: int64
0    67863
1      103
Name: Home Services, dtype: int64
0    67859
1      107
Name: Jazz & Blues, dtype: int64
0    67917
1       49
Name: Massage, dtype: int64
0    67937
1       29
Name: Arts & Crafts, dtype: int64
0    67872
1       94
Name: Brazilian, dtype: int64
0    67927
1       39
Name: Stadiums & Arenas, dtype: int64
0    67958
1        8
Name: Bocce Ball, dtype: int64
0    67736
1      230
Name: Street Vendors, dtype: int64
0    67713
1      253
Name: Bistros, dtype: int64
0    67961
1        5
Name: Coffee & Tea Supplies, dtype: int64
0    67741
1      225
Name: Taiwanese, dtype: int64
0    67919
1       47
Name: Candy Stores, dtype: int64
0    64609
1     3357
Name: Chicken Wings, dtype: int64
0    67706
1      260
Name: Filipino, dtype: int64
0    67963
1        3
Name: Police Departments, dtype: int64
0    67962
1        4
Name: Auto Glass Services, dtype: int64
0    67956
1       10
Name: Czech, dtype: int64
0    67957
1        9
Name: Supper Clubs, dtype: int64
0    67952
1       14
Name: Flea Markets, dtype: int64
0    67263
1      703
Name: Venues & Event Spaces, dtype: int64
0    57702
1    10264
Name: Fast Food, dtype: int64
0    67939
1       27
Name: Appliances & Repair, dtype: int64
0    66747
1     1219
Name: Vegan, dtype: int64
0    67947
1       19
Name: Pop-Up Restaurants, dtype: int64
0    57872
1    10094
Name: Bars, dtype: int64
0    67955
1       11
Name: Olive Oil, dtype: int64
0    67889
1       77
Name: Cupcakes, dtype: int64
0    60731
1     7235
Name: Breakfast & Brunch, dtype: int64
0    67954
1       12
Name: Gyms, dtype: int64
0    67960
1        6
Name: Marinas, dtype: int64
0    67900
1       66
Name: Mags, dtype: int64
0    67954
1       12
Name: Web Design, dtype: int64
0    67959
1        7
Name: Grilling Equipment, dtype: int64
0    67772
1      194
Name: Meat Shops, dtype: int64
0    67787
1      179
Name: British, dtype: int64
0    67788
1      178
Name: Health Markets, dtype: int64
0    65517
1     2449
Name: Asian Fusion, dtype: int64
0    67961
1        5
Name: Public Transportation, dtype: int64
0    67920
1       46
Name: Colombian, dtype: int64
0    65783
1     2183
Name: Barbeque, dtype: int64
0    67956
1       10
Name: Used, dtype: int64
0    67894
1       72
Name: Brewpubs, dtype: int64
0    67936
1       30
Name: Appliances, dtype: int64
0    66883
1     1083
Name: Lounges, dtype: int64
0    67696
1      270
Name: Cheesesteaks, dtype: int64
0    67955
1       11
Name: Cannabis Clinics, dtype: int64
0    67913
1       53
Name: Hungarian, dtype: int64
0    67686
1      280
Name: Food Court, dtype: int64
0    67954
1       12
Name: Pet Services, dtype: int64
0    67960
1        6
Name: Race Tracks, dtype: int64
0    67794
1      172
Name: Kebab, dtype: int64
0    67810
1      156
Name: Arcades, dtype: int64
0    64966
1     3000
Name: Seafood, dtype: int64
0    67962
1        4
Name: Tobacco Shops, dtype: int64
0    67959
1        7
Name: Currency Exchange, dtype: int64
0    67719
1      247
Name: Bubble Tea, dtype: int64
0    67952
1       14
Name: Golf Lessons, dtype: int64
0    66655
1     1311
Name: Juice Bars & Smoothies, dtype: int64
0    67945
1       21
Name: Wine Tasting Room, dtype: int64
0    67907
1       59
Name: Chocolatiers & Shops, dtype: int64
0    67955
1       11
Name: Real Estate Services, dtype: int64
0    67511
1      455
Name: Music Venues, dtype: int64
0    67961
1        5
Name: Diagnostic Services, dtype: int64
0    65397
1     2569
Name: Sushi Bars, dtype: int64
0    67905
1       61
Name: Cafeteria, dtype: int64
0    66771
1     1195
Name: Ice Cream & Frozen Yogurt, dtype: int64
0    67963
1        3
Name: Trinidadian, dtype: int64
0    67954
1       12
Name: Shaved Snow, dtype: int64
0    66493
1     1473
Name: Wine & Spirits, dtype: int64
0    67947
1       19
Name: Public Markets, dtype: int64
0    67952
1       14
Name: Reflexology, dtype: int64
0    67901
1       65
Name: Drugstores, dtype: int64
0    67915
1       51
Name: Florists, dtype: int64
0    66067
1     1899
Name: Bakeries, dtype: int64
0    67709
1      257
Name: Poutineries, dtype: int64
0    67959
1        7
Name: Distilleries, dtype: int64
0    67939
1       27
Name: Comedy Clubs, dtype: int64
0    66742
1     1224
Name: Soup, dtype: int64
0    67505
1      461
Name: Tapas Bars, dtype: int64
0    67944
1       22
Name: Massage Therapy, dtype: int64
0    67950
1       16
Name: Shanghainese, dtype: int64
0    67914
1       52
Name: Kitchen & Bath, dtype: int64
0    67957
1        9
Name: Truck Rental, dtype: int64
0    67719
1      247
Name: Hotels, dtype: int64
0    67957
1        9
Name: Handyman, dtype: int64
0    67883
1       83
Name: Seafood Markets, dtype: int64
0    67928
1       38
Name: Venezuelan, dtype: int64
0    67852
1      114
Name: Internet Cafes, dtype: int64
0    67958
1        8
Name: Summer Camps, dtype: int64
0    67962
1        4
Name: Swiss Food, dtype: int64
0    67956
1       10
Name: Financial Services, dtype: int64
0    67869
1       97
Name: Flowers & Gifts, dtype: int64
0    67951
1       15
Name: Tabletop Games, dtype: int64
0    67877
1       89
Name: Acai Bowls, dtype: int64
0    67895
1       71
Name: Themed Cafes, dtype: int64
0    67190
1      776
Name: Hot Dogs, dtype: int64
0    67900
1       66
Name: Music & Video, dtype: int64
0    67888
1       78
Name: Himalayan/Nepalese, dtype: int64
0    67955
1       11
Name: Medical Cannabis Referrals, dtype: int64
0    67949
1       17
Name: Cabaret, dtype: int64
0    67953
1       13
Name: Auto Repair, dtype: int64
0    66647
1     1319
Name: Tex-Mex, dtype: int64
0    67947
1       19
Name: Parks, dtype: int64
0    67938
1       28
Name: Fondue, dtype: int64
0    67933
1       33
Name: Puerto Rican, dtype: int64
0    67959
1        7
Name: Check Cashing/Pay-day Loans, dtype: int64
0    62351
1     5615
Name: American (New), dtype: int64
0    67955
1       11
Name: Acupuncture, dtype: int64
0    67950
1       16
Name: Social Clubs, dtype: int64
0    67005
1      961
Name: Buffets, dtype: int64
0    67960
1        6
Name: Lighting Fixtures & Equipment, dtype: int64
0    67954
1       12
Name: Cooking Schools, dtype: int64
0    67960
1        6
Name: Boat Dealers, dtype: int64
0    63214
1     4752
Name: Coffee & Tea, dtype: int64
0    65964
1     2002
Name: Delis, dtype: int64
0    67897
1       69
Name: Automotive, dtype: int64
0    67890
1       76
Name: Delicatessen, dtype: int64
0    67644
1      322
Name: Wraps, dtype: int64
0    67882
1       84
Name: Arabian, dtype: int64
0    67775
1      191
Name: Convenience Stores, dtype: int64
0    65929
1     2037
Name: Steakhouses, dtype: int64
0    67956
1       10
Name: Lakes, dtype: int64
0    67947
1       19
Name: Bar Crawl, dtype: int64
0    67807
1      159
Name: Karaoke, dtype: int64
0    67618
1      348
Name: Cajun/Creole, dtype: int64
0    67938
1       28
Name: Community Service/Non-Profit, dtype: int64
0    67956
1       10
Name: Adult Education, dtype: int64
0    67957
1        9
Name: Eyebrow Services, dtype: int64

0    67003
1      963
Name: Ethnic Food, dtype: int64
0    67921
1       45
Name: Nail Salons, dtype: int64
0    67908
1       58
Name: Education, dtype: int64
0    67959
1        7
Name: Comic Books, dtype: int64
0    67959
1        7
Name: Outdoor Furniture Stores, dtype: int64
0    67864
1      102
Name: Polish, dtype: int64
0    67949
1       17
Name: Nail Technicians, dtype: int64
0    67889
1       77
Name: Argentine, dtype: int64
0    67958
1        8
Name: Flooring, dtype: int64
0    67905
1       61
Name: Pool Halls, dtype: int64
0    67961
1        5
Name: Mobile Phones, dtype: int64
0    67959
1        7
Name: Iberian, dtype: int64
0    67950
1       16
Name: Vinyl Records, dtype: int64
0    67961
1        5
Name: Transportation, dtype: int64
0    67938
1       28
Name: Real Estate, dtype: int64
0    67960
1        6
Name: Women's Clothing, dtype: int64
0    67937
1       29
Name: Festivals, dtype: int64
0    67899
1       67
Name: Shaved Ice, dtype: int64
0    67957
1        9
Name: Kitchen Supplies, dtype: int64
0    67887
1       79
Name: Beer Gardens, dtype: int64
0    67942
1       24
Name: Ukrainian, dtype: int64
0    67271
1      695
Name: Latin American, dtype: int64
0    67949
1       17
Name: Herbs & Spices, dtype: int64
0    67951
1       15
Name: Laundry Services, dtype: int64
0    67928
1       38
Name: Fitness & Instruction, dtype: int64
0    67199
1      767
Name: Caribbean, dtype: int64
0    67145
1      821
Name: Halal, dtype: int64
0    67926
1       40
Name: Dinner Theater, dtype: int64
0    67814
1      152
Name: Hookah Bars, dtype: int64
0    67891
1       75
Name: Butcher, dtype: int64
0    67857
1      109
Name: Patisserie/Cake Shop, dtype: int64
0    67948
1       18
Name: Antiques, dtype: int64
0    67894
1       72
Name: Do-It-Yourself Food, dtype: int64
0    67790
1      176
Name: Afghan, dtype: int64
0    67208
1      758
Name: Noodles, dtype: int64
0    67934
1       32
Name: Gift Shops, dtype: int64
0    50067
1    17899
Name: Food, dtype: int64
0    62883
1     5083
Name: Chinese, dtype: int64
0    65821
1     2145
Name: Mediterranean, dtype: int64
0    67842
1      124
Name: New Mexican Cuisine, dtype: int64
0    67928
1       38
Name: Amusement Parks, dtype: int64
0    67960
1        6
Name: Catalan, dtype: int64
0    67955
1       11
Name: Pain Management, dtype: int64
0    67916
1       50
Name: Adult Entertainment, dtype: int64
0    67795
1      171
Name: Pasta Shops, dtype: int64
0    67953
1       13
Name: Barbers, dtype: int64
0    66312
1     1654
Name: Vegetarian, dtype: int64
0    67195
1      771
Name: Food Trucks, dtype: int64
0    67958
1        8
Name: Foundation Repair, dtype: int64
0    67963
1        3
Name: Banks & Credit Unions, dtype: int64
0    67957
1        9
Name: Car Rental, dtype: int64
0    67955
1       11
Name: Horse Racing, dtype: int64
0    67910
1       56
Name: Gelato, dtype: int64
0    67959
1        7
Name: Pet Adoption, dtype: int64
0    67956
1       10
Name: Art Schools, dtype: int64
0    67878
1       88
Name: Ethiopian, dtype: int64
0    67727
1      239
Name: Spanish, dtype: int64
0    67836
1      130
Name: German, dtype: int64
0    67936
1       30
Name: Indonesian, dtype: int64
0    67960
1        6
Name: Paint & Sip, dtype: int64
0    67948
1       18
Name: Office Equipment, dtype: int64
0    67948
1       18
Name: Conveyor Belt Sushi, dtype: int64
0    67931
1       35
Name: Macarons, dtype: int64
0    67953
1       13
Name: Hardware Stores, dtype: int64
0    67105
1      861
Name: Food Delivery Services, dtype: int64
0    67904
1       62
Name: Art Galleries, dtype: int64
0    67849
1      117
Name: Coffee Roasteries, dtype: int64
0    67897
1       69
Name: Tours, dtype: int64
0    67953
1       13
Name: Photography Stores & Services, dtype: int64
0    67961
1        5
Name: Body Shops, dtype: int64
0    67960
1        6
Name: Strip Clubs, dtype: int64
0    67954
1       12
Name: Advertising, dtype: int64
0    67954
1       12
Name: Burmese, dtype: int64
0    67636
1      330
Name: Breweries, dtype: int64
0    67932
1       34
Name: Personal Chefs, dtype: int64
0    67887
1       79
Name: Health & Medical, dtype: int64
0    67940
1       26
Name: Bowling, dtype: int64
0    67793
1      173
Name: African, dtype: int64
0    67948
1       18
Name: Wine Tours, dtype: int64
0    67921
1       45
Name: Gas Stations, dtype: int64
0    57416
1    10550
Name: Nightlife, dtype: int64
0    67930
1       36
Name: Home Decor, dtype: int64
0    67843
1      123
Name: Home & Garden, dtype: int64
0    67948
1       18
Name: Party Equipment Rentals, dtype: int64
0    66903
1     1063
Name: Korean, dtype: int64
0    67742
1      224
Name: Dance Clubs, dtype: int64
0    67945
1       21
Name: Syrian, dtype: int64
0    67913
1       53
Name: Wholesale Stores, dtype: int64
0    67928
1       38
Name: Dumplings, dtype: int64
0    67948
1       18
Name: Hotel bar, dtype: int64
0    67944
1       22
Name: Sicilian, dtype: int64
0    67963
1        3
Name: Haitian, dtype: int64
0    67956
1       10
Name: Piano Bars, dtype: int64
0    66508
1     1458
Name: Cocktail Bars, dtype: int64
0    67674
1      292
Name: Dive Bars, dtype: int64
0    67956
1       10
Name: Vintage & Consignment, dtype: int64
0    67958
1        8
Name: Vitamins & Supplements, dtype: int64
0    67957
1        9
Name: Jewelry, dtype: int64
0    67955
1       11
Name: Chiropractors, dtype: int64
0    67553
1      413
Name: Soul Food, dtype: int64
0    67889
1       77
Name: Day Spas, dtype: int64
0    67962
1        4
Name: Guest Houses, dtype: int64
0    67962
1        4
Name: Pub Food, dtype: int64
0    67912
1       54
Name: Mongolian, dtype: int64
0    67945
1       21
Name: South African, dtype: int64
0    67961
1        5
Name: Japanese Curry, dtype: int64
0    67867
1       99
Name: Professional Services, dtype: int64
0    67957
1        9
Name: Bookstores, dtype: int64
0    67955
1       11
Name: Couriers & Delivery Services, dtype: int64
0    67587
1      379
Name: Lebanese, dtype: int64
0    66536
1     1430
Name: Middle Eastern, dtype: int64
0    67953
1       13
Name: Building Supplies, dtype: int64
0    67904
1       62
Name: Russian, dtype: int64
0    67944
1       22
Name: Pets, dtype: int64
0    67955
1       11
Name: Music & DVDs, dtype: int64
0    67912
1       54
Name: Wholesalers, dtype: int64
0    67918
1       48
Name: Hair Salons, dtype: int64
0    67936
1       30
Name: Furniture Stores, dtype: int64
0    67960
1        6
Name: Electricians, dtype: int64
0    67943
1       23
Name: Videos & Video Game Rental, dtype: int64
0    64556
1     3410
Name: Event Planning & Services, dtype: int64
0    66305
1     1661
Name: Pubs, dtype: int64
0    67688
1      278
Name: Portuguese, dtype: int64
0    67905
1       61
Name: Malaysian, dtype: int64
0    67957
1        9
Name: Commercial Truck Repair, dtype: int64
0    67959
1        7
Name: Colleges & Universities, dtype: int64
0    67922
1       44
Name: Cambodian, dtype: int64
0    67945
1       21
Name: Yelp Events, dtype: int64
0    67324
1      642
Name: Gastropubs, dtype: int64
0    67957
1        9
Name: Pita, dtype: int64
0    67950
1       16
Name: Ethnic Grocery, dtype: int64
0    67961
1        5
Name: Escape Games, dtype: int64
0    64878
1     3088
Name: Japanese, dtype: int64
0    67953
1       13
Name: Country Dance Halls, dtype: int64
0    67339
1      627
Name: Grocery, dtype: int64
0    67955
1       11
Name: Art Supplies, dtype: int64
0    67823
1      143
Name: Hot Pot, dtype: int64
0    67954
1       12
Name: Sporting Goods, dtype: int64
0    67963
1        3
Name: Hospitals, dtype: int64
0    67949
1       17
Name: Ethical Grocery, dtype: int64
0    67933
1       33
Name: Country Clubs, dtype: int64
0    67941
1       25
Name: Food Tours, dtype: int64
0    67958
1        8
Name: Slovakian, dtype: int64
0    67959
1        7
Name: Cards & Stationery, dtype: int64
0    67954
1       12
Name: Austrian, dtype: int64
0    67955
1       11
Name: Doctors, dtype: int64
0    67596
1      370
Name: Hawaiian, dtype: int64
0    67962
1        4
Name: Libraries, dtype: int64
0    67926
1       40
Name: Wigs, dtype: int64
0    66593
1     1373
Name: Wine Bars, dtype: int64
0    67961
1        5
Name: Synagogues, dtype: int64
0    67961
1        5
Name: Car Dealers, dtype: int64
0    67962
1        4
Name: Junk Removal & Hauling, dtype: int64
0    67780
1      186
Name: Party & Event Planning, dtype: int64
0    67955
1       11
Name: Art Classes, dtype: int64
0    67586
1      380
Name: Hotels & Travel, dtype: int64
0    67898
1       68
Name: Shopping Centers, dtype: int64
0    67951
1       15
Name: Musicians, dtype: int64
0    67938
1       28
Name: Public Services & Government, dtype: int64
0    67923
1       43
Name: Donairs, dtype: int64
0    67930
1       36
Name: Contractors, dtype: int64
0    67956
1       10
Name: Amateur Sports Teams, dtype: int64
0    67899
1       67
Name: Performing Arts, dtype: int64
0    67937
1       29
Name: Beverage Store, dtype: int64
0    67853
1      113
Name: Local Services, dtype: int64
0    67934
1       32
Name: Wedding Planning, dtype: int64
0    67941
1       25
Name: Singaporean, dtype: int64
0    66733
1     1233
Name: Greek, dtype: int64
0    67922
1       44
Name: Gay Bars, dtype: int64
0    67961
1        5
Name: Outlet Stores, dtype: int64
0    65985
1     1981
Name: Sports Bars, dtype: int64
0    67959
1        7
Name: Animal Shelters, dtype: int64
0    67264
1      702
Name: Shopping, dtype: int64
0    67944
1       22
Name: Specialty Schools, dtype: int64
0    67959
1        7
Name: Historical Tours, dtype: int64
0    67946
1       20
Name: Team Building Activities, dtype: int64
0    66843
1     1123
Name: Gluten-Free, dtype: int64
0    67454
1      512
Name: Pakistani, dtype: int64
0    67931
1       35
Name: Fruits & Veggies, dtype: int64
0    67934
1       32
Name: Bed & Breakfast, dtype: int64
0    67903
1       63
Name: Organic Stores, dtype: int64
0    67922
1       44
Name: Wineries, dtype: int64
0    61559
1     6407
Name: Mexican, dtype: int64
0    67877
1       89
Name: Smokehouse, dtype: int64
0    67890
1       76
Name: Hakka, dtype: int64
0    67823
1      143
Name: Kosher, dtype: int64
0    65624
1     2342
Name: Caterers, dtype: int64
0    67948
1       18
Name: Discount Store, dtype: int64
0    67954
1       12
Name: Soba, dtype: int64

In [189]:
new_attributes_table_2 = pandas.merge(new_attributes_table,new_df_2,how="inner",on="business_id")

In [190]:
new_attributes_table_2.head()

,business_id,name,byob,bikeparking,businessacceptsbitcoin,businessacceptscreditcards,byappointmentonly,caters,coatcheck,corkage,...,Bed & Breakfast,Organic Stores,Wineries,Mexican,Smokehouse,Hakka,Kosher,Caterers,Discount Store,Soba
0,rVBPQdeayMYht4Uv_FOLHg,Gourmet Burger Company,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,rVBPQdeayMYht4Uv_FOLHg,Gourmet Burger Company,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,rVBPQdeayMYht4Uv_FOLHg,Gourmet Burger Company,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,98hyK2QEUeI8v2y0AghfZA,Pho Lee's Vietnamese Restaurant,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,98hyK2QEUeI8v2y0AghfZA,Pho Lee's Vietnamese Restaurant,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [199]:
for i in new_attributes_table_2.drop_duplicates().drop(["business_id","name"], axis = 1).columns:
    print(new_attributes_table_2[i].value_counts())

0    54265
1       86
Name: byob, dtype: int64
1    31079
0    23272
Name: bikeparking, dtype: int64
0    54273
1       78
Name: businessacceptsbitcoin, dtype: int64
1    33451
0    20900
Name: businessacceptscreditcards, dtype: int64
0    54219
1      132
Name: byappointmentonly, dtype: int64
0    33787
1    20564
Name: caters, dtype: int64
0    53996
1      355
Name: coatcheck, dtype: int64
0    54108
1      243
Name: corkage, dtype: int64
0    52592
1     1759
Name: dogsallowed, dtype: int64
0    53097
1     1254
Name: drivethru, dtype: int64
0    53899
1      452
Name: goodfordancing, dtype: int64
1    41889
0    12462
Name: goodforkids, dtype: int64
0    45138
1     9213
Name: happyhour, dtype: int64
1    38077
0    16274
Name: hastv, dtype: int64
0    54337
1       14
Name: open24hours, dtype: int64
0    33687
1    20664
Name: outdoorseating, dtype: int64
0    54341
1       10
Name: restaurantscounterservice, dtype: int64
0    35346
1    19005
Name: restaurantsdelivery, dtype: int64
1    43708
0    10643
Name: restaurantsgoodforgroups, dtype: int64
0    34590
1    19761
Name: restaurantsreservations, dtype: int64
0    40503
1    13848
Name: restaurantstableservice, dtype: int64
1    47987
0     6364
Name: restaurantstakeout, dtype: int64
0    53005
1     1346
Name: smoking, dtype: int64
0    43809
1    10542
Name: wheelchairaccessible, dtype: int64
1    30029
0    24322
Name: alcohol_false, dtype: int64
0    47659
1     6692
Name: alcohol_beer_and_wine, dtype: int64
0    36721
1    17630
Name: alcohol_full_bar, dtype: int64
1    53576
0      775
Name: byobcorkage_false, dtype: int64
0    54154
1      197
Name: byobcorkage_yes_corkage, dtype: int64
0    53773
1      578
Name: byobcorkage_yes_free, dtype: int64
1    40928
0    13423
Name: noiselevel_average, dtype: int64
0    50952
1     3399
Name: noiselevel_loud, dtype: int64
0    45441
1     8910
Name: noiselevel_quiet, dtype: int64
0    53237
1     1114
Name: noiselevel_very_loud, dtype: int64
1    46484
0     7867
Name: restaurantsattire_casual, dtype: int64
0    53140
1     1211
Name: restaurantsattire_dressy, dtype: int64
0    54240
1      111
Name: restaurantsattire_formal, dtype: int64
0    47806
1     6545
Name: restaurantsattire_no_dress_code, dtype: int64
0    34325
1    20026
Name: restaurantspricerange2_$10_and_under, dtype: int64
0    27337
1    27014
Name: restaurantspricerange2_$11_to_30, dtype: int64
0    51868
1     2483
Name: restaurantspricerange2_$31_to_60, dtype: int64
0    53955
1      396
Name: restaurantspricerange2_$61_and_over, dtype: int64
1    32296
0    22055
Name: wifi_false, dtype: int64
0    32572
1    21779
Name: wifi_free, dtype: int64
0    54075
1      276
Name: wifi_paid, dtype: int64
0    53169
1     1182
Name: hipster, dtype: int64
0    47598
1     6753
Name: classy, dtype: int64
0    53663
1      688
Name: intimate, dtype: int64
0    51455
1     2896
Name: trendy, dtype: int64
0    31326
1    23025
Name: casual, dtype: int64
0    54008
1      343
Name: touristy, dtype: int64
0    53577
1      774
Name: divey, dtype: int64
0    53656
1      695
Name: romantic, dtype: int64
0    53736
1      615
Name: upscale, dtype: int64
0    54338
1       13
Name: Guamanian, dtype: int64
0    54337
1       14
Name: Bangladeshi, dtype: int64
0    54351
Name: Walking Tours, dtype: int64
0    54332
1       19
Name: Resorts, dtype: int64
0    53801
1      550
Name: Beer Bar, dtype: int64
0    54340
1       11
Name: Cooking Classes, dtype: int64
0    54215
1      136
Name: Casinos, dtype: int64
0    54343
1        8
Name: Department Stores, dtype: int64
0    54351
Name: Medical Centers, dtype: int64
0    52959
1     1392
Name: Thai, dtype: int64
0    54340
1       11
Name: Pretzels, dtype: int64
0    54351
Name: Studio Taping, dtype: int64
0    54139
1      212
Name: Food Stands, dtype: int64
0    54236
1      115
Name: Salvadoran, dtype: int64
0    54351
Name: Auto Parts & Supplies, dtype: int64
0    54272
1       79
Name: Cuban, dtype: int64
0    54169
1      182
Name: Donuts, dtype: int64
0    54346
1        5
Name: Sugar Shacks, dtype: int64
0    54351
Name: Heating & Air Conditioning/HVAC, dtype: int64
0    52801
1     1550
Name: Diners, dtype: int64
0    54348
1        3
Name: Eritrean, dtype: int64
0    54341
1       10
Name: Armenian, dtype: int64
0    54302
1       49
Name: Indoor Playcentre, dtype: int64
0    54346
1        5
Name: Custom Cakes, dtype: int64
0    50988
1     3363
Name: Salad, dtype: int64
0    54331
1       20
Name: Laotian, dtype: int64
0    52627
1     1724
Name: Specialty Food, dtype: int64
0    54351
Name: Laboratory Testing, dtype: int64
0    54344
1        7
Name: Physical Therapy, dtype: int64
0    54351
Name: Knife Sharpening, dtype: int64
0    54193
1      158
Name: Irish, dtype: int64
0    54316
1       35
Name: Kids Activities, dtype: int64
0    54351
Name: Masonry/Concrete, dtype: int64
0    54351
Name: Campgrounds, dtype: int64
0    49905
1     4446
Name: Italian, dtype: int64
0    54347
1        4
Name: Thrift Stores, dtype: int64
0    54174
1      177
Name: Persian/Iranian, dtype: int64
0    54317
1       34
Name: Beauty & Spas, dtype: int64
0    54233
1      118
Name: Szechuan, dtype: int64
0    54344
1        7
Name: Empanadas, dtype: int64
0    54339
1       12
Name: Nutritionists, dtype: int64
0    51426
1     2925
Name: Cafes, dtype: int64
0    54330
1       21
Name: Cinema, dtype: int64
0    54331
1       20
Name: Dominican, dtype: int64
0    53158
1     1193
Name: Vietnamese, dtype: int64
0    54348
1        3
Name: Senegalese, dtype: int64
0    54214
1      137
Name: Turkish, dtype: int64
0    52590
1     1761
Name: Tacos, dtype: int64
0    54347
1        4
Name: Dry Cleaning & Laundry, dtype: int64
0    53597
1      754
Name: Chicken Shop, dtype: int64
0    52650
1     1701
Name: Canadian (New), dtype: int64
0    54347
1        4
Name: Australian, dtype: int64
0    54344
1        7
Name: Swimming Pools, dtype: int64
0    54281
1       70
Name: Golf, dtype: int64
0    54292
1       59
Name: Live/Raw Food, dtype: int64
0    54339
1       12
Name: Trainers, dtype: int64
0    54332
1       19
Name: Farmers Market, dtype: int64
0    54260
1       91
Name: Belgian, dtype: int64
0    54351
Name: Cosmetics & Beauty Supply, dtype: int64
0    52986
1     1365
Name: Indian, dtype: int64
0    54326
1       25
Name: Basque, dtype: int64
0    54351
Name: Eyelash Service, dtype: int64
0    54303
1       48
Name: Moroccan, dtype: int64
0    53783
1      568
Name: Southern, dtype: int64
0    54306
1       45
Name: International Grocery, dtype: int64
0    54249
1      102
Name: Pan Asian, dtype: int64
0    53763
1      588
Name: Tapas/Small Plates, dtype: int64
0    52737
1     1614
Name: Desserts, dtype: int64
0    54265
1       86
Name: Irish Pub, dtype: int64
0    54099
1      252
Name: Local Flavor, dtype: int64
0    54351
Name: Medical Spas, dtype: int64
0    54351
Name: Naturopathic/Holistic, dtype: int64
0    54319
1       32
Name: Sri Lankan, dtype: int64
0    54322
1       29
Name: Fashion, dtype: int64
0    54295
1       56
Name: International, dtype: int64
0    53448
1      903
Name: Comfort Food, dtype: int64
0    54344
1        7
Name: Churches, dtype: int64
0    54339
1       12
Name: Interior Design, dtype: int64
1    54351
Name: Restaurants, dtype: int64
0    54339
1       12
Name: Hobby Shops, dtype: int64
0    54054
1      297
Name: Ramen, dtype: int64
0    54351
Name: Paint-Your-Own Pottery, dtype: int64
0    54351
Name: Hair Loss Centers, dtype: int64
0    48355
1     5996
Name: Pizza, dtype: int64
0    54351
Name: Skin Care, dtype: int64
0    54351
Name: Skydiving, dtype: int64
0    54305
1       46
Name: Hong Kong Style Cafe, dtype: int64
0    54344
1        7
Name: Polynesian, dtype: int64
0    54313
1       38
Name: Izakaya, dtype: int64
0    54109
1      242
Name: Imported Food, dtype: int64
0    54316
1       35
Name: Pancakes, dtype: int64
0    53345
1     1006
Name: Arts & Entertainment, dtype: int64
0    54055
1      296
Name: Bagels, dtype: int64
0    54351
Name: Estate Liquidation, dtype: int64
0    54184
1      167
Name: Poke, dtype: int64
0    54032
1      319
Name: Fish & Chips, dtype: int64
0    54344
1        7
Name: Tiki Bars, dtype: int64
0    54351
Name: Hair Stylists, dtype: int64
0    54342
1        9
Name: Pharmacy, dtype: int64
0    54347
1        4
Name: Hainan, dtype: int64
0    54316
1       35
Name: Whiskey Bars, dtype: int64
0    54351
Name: Car Wash, dtype: int64
0    54237
1      114
Name: Peruvian, dtype: int64
0    54213
1      138
Name: Waffles, dtype: int64
0    54319
1       32
Name: Books, dtype: int64
0    54351
Name: Boat Repair, dtype: int64
0    54193
1      158
Name: Cantonese, dtype: int64
0    54218
1      133
Name: Falafel, dtype: int64
0    46848
1     7503
Name: American (Traditional), dtype: int64
0    47001
1     7350
Name: Sandwiches, dtype: int64
0    53355
1      996
Name: French, dtype: int64
0    54104
1      247
Name: Modern European, dtype: int64
0    54338
1       13
Name: Scandinavian, dtype: int64
0    54351
Name: Weight Loss Centers, dtype: int64
0    54319
1       32
Name: Teppanyaki, dtype: int64
0    47579
1     6772
Name: Burgers, dtype: int64
0    54346
1        5
Name: Airport Lounges, dtype: int64
0    54001
1      350
Name: Dim Sum, dtype: int64
0    53019
1     1332
Name: Beer, dtype: int64
0    54145
1      206
Name: Active Life, dtype: int64
0    54351
Name: Waxing, dtype: int64
0    54334
1       17
Name: Party Supplies, dtype: int64
0    54208
1      143
Name: Brasseries, dtype: int64
0    54351
Name: Mattresses, dtype: int64
0    54340
1       11
Name: Shared Office Spaces, dtype: int64
0    54351
Name: Community Centers, dtype: int64
0    54351
Name: Restaurant Supplies, dtype: int64
0    54109
1      242
Name: Creperies, dtype: int64
0    54345
1        6
Name: Speakeasies, dtype: int64
0    54310
1       41
Name: Cheese Shops, dtype: int64
0    54335
1       16
Name: Airports, dtype: int64
0    54319
1       32
Name: Egyptian, dtype: int64
0    54335
1       16
Name: Religious Organizations, dtype: int64
0    54351
Name: Hair Removal, dtype: int64
0    54248
1      103
Name: Tea Rooms, dtype: int64
0    54328
1       23
Name: Home Services, dtype: int64
0    54260
1       91
Name: Jazz & Blues, dtype: int64
0    54351
Name: Massage, dtype: int64
0    54340
1       11
Name: Arts & Crafts, dtype: int64
0    54270
1       81
Name: Brazilian, dtype: int64
0    54330
1       21
Name: Stadiums & Arenas, dtype: int64
0    54351
Name: Bocce Ball, dtype: int64
0    54225
1      126
Name: Street Vendors, dtype: int64
0    54136
1      215
Name: Bistros, dtype: int64
0    54346
1        5
Name: Coffee & Tea Supplies, dtype: int64
0    54189
1      162
Name: Taiwanese, dtype: int64
0    54334
1       17
Name: Candy Stores, dtype: int64
0    51703
1     2648
Name: Chicken Wings, dtype: int64
0    54152
1      199
Name: Filipino, dtype: int64
0    54351
Name: Police Departments, dtype: int64
0    54351
Name: Auto Glass Services, dtype: int64
0    54345
1        6
Name: Czech, dtype: int64
0    54351
Name: Supper Clubs, dtype: int64
0    54337
1       14
Name: Flea Markets, dtype: int64
0    53806
1      545
Name: Venues & Event Spaces, dtype: int64
0    46088
1     8263
Name: Fast Food, dtype: int64

0    54351
Name: Appliances & Repair, dtype: int64
0    53294
1     1057
Name: Vegan, dtype: int64
0    54339
1       12
Name: Pop-Up Restaurants, dtype: int64
0    45037
1     9314
Name: Bars, dtype: int64
0    54340
1       11
Name: Olive Oil, dtype: int64
0    54308
1       43
Name: Cupcakes, dtype: int64
0    47868
1     6483
Name: Breakfast & Brunch, dtype: int64
0    54339
1       12
Name: Gyms, dtype: int64
0    54351
Name: Marinas, dtype: int64
0    54319
1       32
Name: Mags, dtype: int64
0    54339
1       12
Name: Web Design, dtype: int64
0    54351
Name: Grilling Equipment, dtype: int64
0    54247
1      104
Name: Meat Shops, dtype: int64
0    54187
1      164
Name: British, dtype: int64
0    54252
1       99
Name: Health Markets, dtype: int64
0    52171
1     2180
Name: Asian Fusion, dtype: int64
0    54351
Name: Public Transportation, dtype: int64
0    54305
1       46
Name: Colombian, dtype: int64
0    52524
1     1827
Name: Barbeque, dtype: int64
0    54341
1       10
Name: Used, dtype: int64
0    54287
1       64
Name: Brewpubs, dtype: int64
0    54351
Name: Appliances, dtype: int64
0    53405
1      946
Name: Lounges, dtype: int64
0    54112
1      239
Name: Cheesesteaks, dtype: int64
0    54351
Name: Cannabis Clinics, dtype: int64
0    54300
1       51
Name: Hungarian, dtype: int64
0    54147
1      204
Name: Food Court, dtype: int64
0    54351
Name: Pet Services, dtype: int64
0    54345
1        6
Name: Race Tracks, dtype: int64
0    54191
1      160
Name: Kebab, dtype: int64
0    54211
1      140
Name: Arcades, dtype: int64
0    51635
1     2716
Name: Seafood, dtype: int64
0    54347
1        4
Name: Tobacco Shops, dtype: int64
0    54344
1        7
Name: Currency Exchange, dtype: int64
0    54200
1      151
Name: Bubble Tea, dtype: int64
0    54343
1        8
Name: Golf Lessons, dtype: int64
0    53367
1      984
Name: Juice Bars & Smoothies, dtype: int64
0    54330
1       21
Name: Wine Tasting Room, dtype: int64
0    54324
1       27
Name: Chocolatiers & Shops, dtype: int64
0    54351
Name: Real Estate Services, dtype: int64
0    53918
1      433
Name: Music Venues, dtype: int64
0    54351
Name: Diagnostic Services, dtype: int64
0    52144
1     2207
Name: Sushi Bars, dtype: int64
0    54306
1       45
Name: Cafeteria, dtype: int64
0    53509
1      842
Name: Ice Cream & Frozen Yogurt, dtype: int64
0    54348
1        3
Name: Trinidadian, dtype: int64
0    54351
Name: Shaved Snow, dtype: int64
0    53019
1     1332
Name: Wine & Spirits, dtype: int64
0    54332
1       19
Name: Public Markets, dtype: int64
0    54351
Name: Reflexology, dtype: int64
0    54306
1       45
Name: Drugstores, dtype: int64
0    54330
1       21
Name: Florists, dtype: int64
0    53093
1     1258
Name: Bakeries, dtype: int64
0    54124
1      227
Name: Poutineries, dtype: int64
0    54344
1        7
Name: Distilleries, dtype: int64
0    54336
1       15
Name: Comedy Clubs, dtype: int64
0    53218
1     1133
Name: Soup, dtype: int64
0    53940
1      411
Name: Tapas Bars, dtype: int64
0    54351
Name: Massage Therapy, dtype: int64
0    54335
1       16
Name: Shanghainese, dtype: int64
0    54331
1       20
Name: Kitchen & Bath, dtype: int64
0    54342
1        9
Name: Truck Rental, dtype: int64
0    54250
1      101
Name: Hotels, dtype: int64
0    54351
Name: Handyman, dtype: int64
0    54285
1       66
Name: Seafood Markets, dtype: int64
0    54313
1       38
Name: Venezuelan, dtype: int64
0    54262
1       89
Name: Internet Cafes, dtype: int64
0    54343
1        8
Name: Summer Camps, dtype: int64
0    54347
1        4
Name: Swiss Food, dtype: int64
0    54344
1        7
Name: Financial Services, dtype: int64
0    54319
1       32
Name: Flowers & Gifts, dtype: int64
0    54341
1       10
Name: Tabletop Games, dtype: int64
0    54280
1       71
Name: Acai Bowls, dtype: int64
0    54291
1       60
Name: Themed Cafes, dtype: int64
0    53701
1      650
Name: Hot Dogs, dtype: int64
0    54319
1       32
Name: Music & Video, dtype: int64
0    54283
1       68
Name: Himalayan/Nepalese, dtype: int64
0    54351
Name: Medical Cannabis Referrals, dtype: int64
0    54334
1       17
Name: Cabaret, dtype: int64
0    54342
1        9
Name: Auto Repair, dtype: int64
0    53197
1     1154
Name: Tex-Mex, dtype: int64
0    54351
Name: Parks, dtype: int64
0    54332
1       19
Name: Fondue, dtype: int64
0    54318
1       33
Name: Puerto Rican, dtype: int64
0    54344
1        7
Name: Check Cashing/Pay-day Loans, dtype: int64
0    49263
1     5088
Name: American (New), dtype: int64
0    54351
Name: Acupuncture, dtype: int64
0    54339
1       12
Name: Social Clubs, dtype: int64
0    53512
1      839
Name: Buffets, dtype: int64
0    54351
Name: Lighting Fixtures & Equipment, dtype: int64
0    54339
1       12
Name: Cooking Schools, dtype: int64
0    54351
Name: Boat Dealers, dtype: int64
0    50989
1     3362
Name: Coffee & Tea, dtype: int64
0    52738
1     1613
Name: Delis, dtype: int64
0    54318
1       33
Name: Automotive, dtype: int64
0    54303
1       48
Name: Delicatessen, dtype: int64
0    54046
1      305
Name: Wraps, dtype: int64
0    54277
1       74
Name: Arabian, dtype: int64
0    54208
1      143
Name: Convenience Stores, dtype: int64
0    52496
1     1855
Name: Steakhouses, dtype: int64
0    54351
Name: Lakes, dtype: int64
0    54332
1       19
Name: Bar Crawl, dtype: int64
0    54231
1      120
Name: Karaoke, dtype: int64
0    54078
1      273
Name: Cajun/Creole, dtype: int64
0    54333
1       18
Name: Community Service/Non-Profit, dtype: int64
0    54341
1       10
Name: Adult Education, dtype: int64
0    54351
Name: Eyebrow Services, dtype: int64
0    53590
1      761
Name: Ethnic Food, dtype: int64
0    54346
1        5
Name: Nail Salons, dtype: int64
0    54317
1       34
Name: Education, dtype: int64
0    54344
1        7
Name: Comic Books, dtype: int64
0    54351
Name: Outdoor Furniture Stores, dtype: int64
0    54270
1       81
Name: Polish, dtype: int64
0    54351
Name: Nail Technicians, dtype: int64
0    54274
1       77
Name: Argentine, dtype: int64
0    54351
Name: Flooring, dtype: int64
0    54298
1       53
Name: Pool Halls, dtype: int64
0    54351
Name: Mobile Phones, dtype: int64
0    54344
1        7
Name: Iberian, dtype: int64
0    54335
1       16
Name: Vinyl Records, dtype: int64
0    54351
Name: Transportation, dtype: int64
0    54340
1       11
Name: Real Estate, dtype: int64
0    54345
1        6
Name: Women's Clothing, dtype: int64
0    54346
1        5
Name: Festivals, dtype: int64
0    54305
1       46
Name: Shaved Ice, dtype: int64
0    54342
1        9
Name: Kitchen Supplies, dtype: int64
0    54272
1       79
Name: Beer Gardens, dtype: int64
0    54327
1       24
Name: Ukrainian, dtype: int64
0    53729
1      622
Name: Latin American, dtype: int64
0    54340
1       11
Name: Herbs & Spices, dtype: int64
0    54351
Name: Laundry Services, dtype: int64
0    54319
1       32
Name: Fitness & Instruction, dtype: int64
0    53769
1      582
Name: Caribbean, dtype: int64
0    53678
1      673
Name: Halal, dtype: int64
0    54323
1       28
Name: Dinner Theater, dtype: int64
0    54214
1      137
Name: Hookah Bars, dtype: int64
0    54301
1       50
Name: Butcher, dtype: int64
0    54296
1       55
Name: Patisserie/Cake Shop, dtype: int64
0    54333
1       18
Name: Antiques, dtype: int64
0    54297
1       54
Name: Do-It-Yourself Food, dtype: int64
0    54194
1      157
Name: Afghan, dtype: int64
0    53667
1      684
Name: Noodles, dtype: int64
0    54340
1       11
Name: Gift Shops, dtype: int64
0    40906
1    13445
Name: Food, dtype: int64
0    50192
1     4159
Name: Chinese, dtype: int64
0    52540
1     1811
Name: Mediterranean, dtype: int64
0    54247
1      104
Name: New Mexican Cuisine, dtype: int64
0    54329
1       22
Name: Amusement Parks, dtype: int64
0    54351
Name: Catalan, dtype: int64
0    54351
Name: Pain Management, dtype: int64
0    54311
1       40
Name: Adult Entertainment, dtype: int64
0    54200
1      151
Name: Pasta Shops, dtype: int64
0    54344
1        7
Name: Barbers, dtype: int64
0    52865
1     1486
Name: Vegetarian, dtype: int64
0    53924
1      427
Name: Food Trucks, dtype: int64
0    54351
Name: Foundation Repair, dtype: int64
0    54351
Name: Banks & Credit Unions, dtype: int64
0    54342
1        9
Name: Car Rental, dtype: int64
0    54345
1        6
Name: Horse Racing, dtype: int64
0    54307
1       44
Name: Gelato, dtype: int64
0    54351
Name: Pet Adoption, dtype: int64
0    54341
1       10
Name: Art Schools, dtype: int64
0    54271
1       80
Name: Ethiopian, dtype: int64
0    54148
1      203
Name: Spanish, dtype: int64
0    54241
1      110
Name: German, dtype: int64
0    54321
1       30
Name: Indonesian, dtype: int64
0    54345
1        6
Name: Paint & Sip, dtype: int64
0    54351
Name: Office Equipment, dtype: int64
0    54333
1       18
Name: Conveyor Belt Sushi, dtype: int64
0    54329
1       22
Name: Macarons, dtype: int64
0    54338
1       13
Name: Hardware Stores, dtype: int64
0    53726
1      625
Name: Food Delivery Services, dtype: int64
0    54306
1       45
Name: Art Galleries, dtype: int64
0    54294
1       57
Name: Coffee Roasteries, dtype: int64
0    54333
1       18
Name: Tours, dtype: int64
0    54351
Name: Photography Stores & Services, dtype: int64
0    54346
1        5
Name: Body Shops, dtype: int64
0    54351
Name: Strip Clubs, dtype: int64
0    54339
1       12
Name: Advertising, dtype: int64
0    54341
1       10
Name: Burmese, dtype: int64
0    54041
1      310
Name: Breweries, dtype: int64
0    54334
1       17
Name: Personal Chefs, dtype: int64
0    54323
1       28
Name: Health & Medical, dtype: int64
0    54325
1       26
Name: Bowling, dtype: int64
0    54213
1      138
Name: African, dtype: int64
0    54351
Name: Wine Tours, dtype: int64
0    54323
1       28
Name: Gas Stations, dtype: int64
0    44695
1     9656
Name: Nightlife, dtype: int64
0    54341
1       10
Name: Home Decor, dtype: int64
0    54308
1       43
Name: Home & Garden, dtype: int64
0    54351
Name: Party Equipment Rentals, dtype: int64
0    53446
1      905
Name: Korean, dtype: int64
0    54164
1      187
Name: Dance Clubs, dtype: int64
0    54332
1       19
Name: Syrian, dtype: int64
0    54351
Name: Wholesale Stores, dtype: int64
0    54322
1       29
Name: Dumplings, dtype: int64
0    54333
1       18
Name: Hotel bar, dtype: int64
0    54329
1       22
Name: Sicilian, dtype: int64

0    54351
Name: Haitian, dtype: int64
0    54341
1       10
Name: Piano Bars, dtype: int64
0    52931
1     1420
Name: Cocktail Bars, dtype: int64
0    54080
1      271
Name: Dive Bars, dtype: int64
0    54341
1       10
Name: Vintage & Consignment, dtype: int64
0    54351
Name: Vitamins & Supplements, dtype: int64
0    54351
Name: Jewelry, dtype: int64
0    54351
Name: Chiropractors, dtype: int64
0    54004
1      347
Name: Soul Food, dtype: int64
0    54330
1       21
Name: Day Spas, dtype: int64
0    54351
Name: Guest Houses, dtype: int64
0    54347
1        4
Name: Pub Food, dtype: int64
0    54299
1       52
Name: Mongolian, dtype: int64
0    54334
1       17
Name: South African, dtype: int64
0    54346
1        5
Name: Japanese Curry, dtype: int64
0    54329
1       22
Name: Professional Services, dtype: int64
0    54342
1        9
Name: Bookstores, dtype: int64
0    54345
1        6
Name: Couriers & Delivery Services, dtype: int64
0    54070
1      281
Name: Lebanese, dtype: int64
0    53225
1     1126
Name: Middle Eastern, dtype: int64
0    54351
Name: Building Supplies, dtype: int64
0    54309
1       42
Name: Russian, dtype: int64
0    54341
1       10
Name: Pets, dtype: int64
0    54351
Name: Music & DVDs, dtype: int64
0    54351
Name: Wholesalers, dtype: int64
0    54345
1        6
Name: Hair Salons, dtype: int64
0    54351
Name: Furniture Stores, dtype: int64
0    54351
Name: Electricians, dtype: int64
0    54351
Name: Videos & Video Game Rental, dtype: int64
0    51674
1     2677
Name: Event Planning & Services, dtype: int64
0    52800
1     1551
Name: Pubs, dtype: int64
0    54124
1      227
Name: Portuguese, dtype: int64
0    54294
1       57
Name: Malaysian, dtype: int64
0    54342
1        9
Name: Commercial Truck Repair, dtype: int64
0    54344
1        7
Name: Colleges & Universities, dtype: int64
0    54316
1       35
Name: Cambodian, dtype: int64
0    54342
1        9
Name: Yelp Events, dtype: int64
0    53751
1      600
Name: Gastropubs, dtype: int64
0    54342
1        9
Name: Pita, dtype: int64
0    54342
1        9
Name: Ethnic Grocery, dtype: int64
0    54346
1        5
Name: Escape Games, dtype: int64
0    51694
1     2657
Name: Japanese, dtype: int64
0    54338
1       13
Name: Country Dance Halls, dtype: int64
0    53981
1      370
Name: Grocery, dtype: int64
0    54351
Name: Art Supplies, dtype: int64
0    54223
1      128
Name: Hot Pot, dtype: int64
0    54339
1       12
Name: Sporting Goods, dtype: int64
0    54351
Name: Hospitals, dtype: int64
0    54346
1        5
Name: Ethical Grocery, dtype: int64
0    54331
1       20
Name: Country Clubs, dtype: int64
0    54351
Name: Food Tours, dtype: int64
0    54351
Name: Slovakian, dtype: int64
0    54351
Name: Cards & Stationery, dtype: int64
0    54339
1       12
Name: Austrian, dtype: int64
0    54351
Name: Doctors, dtype: int64
0    54024
1      327
Name: Hawaiian, dtype: int64
0    54351
Name: Libraries, dtype: int64
0    54311
1       40
Name: Wigs, dtype: int64
0    53036
1     1315
Name: Wine Bars, dtype: int64
0    54346
1        5
Name: Synagogues, dtype: int64
0    54351
Name: Car Dealers, dtype: int64
0    54351
Name: Junk Removal & Hauling, dtype: int64
0    54214
1      137
Name: Party & Event Planning, dtype: int64
0    54351
Name: Art Classes, dtype: int64
0    54179
1      172
Name: Hotels & Travel, dtype: int64
0    54320
1       31
Name: Shopping Centers, dtype: int64
0    54336
1       15
Name: Musicians, dtype: int64
0    54345
1        6
Name: Public Services & Government, dtype: int64
0    54326
1       25
Name: Donairs, dtype: int64
0    54351
Name: Contractors, dtype: int64
0    54351
Name: Amateur Sports Teams, dtype: int64
0    54296
1       55
Name: Performing Arts, dtype: int64
0    54322
1       29
Name: Beverage Store, dtype: int64
0    54316
1       35
Name: Local Services, dtype: int64
0    54342
1        9
Name: Wedding Planning, dtype: int64
0    54326
1       25
Name: Singaporean, dtype: int64
0    53320
1     1031
Name: Greek, dtype: int64
0    54307
1       44
Name: Gay Bars, dtype: int64
0    54346
1        5
Name: Outlet Stores, dtype: int64
0    52481
1     1870
Name: Sports Bars, dtype: int64
0    54351
Name: Animal Shelters, dtype: int64
0    53964
1      387
Name: Shopping, dtype: int64
0    54329
1       22
Name: Specialty Schools, dtype: int64
0    54351
Name: Historical Tours, dtype: int64
0    54331
1       20
Name: Team Building Activities, dtype: int64
0    53342
1     1009
Name: Gluten-Free, dtype: int64
0    53932
1      419
Name: Pakistani, dtype: int64
0    54329
1       22
Name: Fruits & Veggies, dtype: int64
0    54344
1        7
Name: Bed & Breakfast, dtype: int64
0    54298
1       53
Name: Organic Stores, dtype: int64
0    54315
1       36
Name: Wineries, dtype: int64
0    48793
1     5558
Name: Mexican, dtype: int64
0    54262
1       89
Name: Smokehouse, dtype: int64
0    54281
1       70
Name: Hakka, dtype: int64
0    54234
1      117
Name: Kosher, dtype: int64
0    52406
1     1945
Name: Caterers, dtype: int64
0    54351
Name: Discount Store, dtype: int64
0    54351
Name: Soba, dtype: int64

In [180]:
attributes_table.duplicated().sum()

0

In [181]:
new_df.duplicated().sum()

0

In [292]:
new_attributes_table_2.columns = [i.lower().replace("-","_").replace(" ","_").replace("\\","_").replace("/","_").replace("&","_").replace("(","").replace(")","") for i in new_attributes_table_2.columns]

In [293]:
for i in new_attributes_table_2.drop(["business_id","name"], axis =1 ).columns:
    print(f"{i} INT NOT NULL,")

byob INT NOT NULL,
bikeparking INT NOT NULL,
businessacceptsbitcoin INT NOT NULL,
businessacceptscreditcards INT NOT NULL,
caters INT NOT NULL,
coatcheck INT NOT NULL,
corkage INT NOT NULL,
dogsallowed INT NOT NULL,
drivethru INT NOT NULL,
goodfordancing INT NOT NULL,
goodforkids INT NOT NULL,
happyhour INT NOT NULL,
hastv INT NOT NULL,
outdoorseating INT NOT NULL,
restaurantsdelivery INT NOT NULL,
restaurantsgoodforgroups INT NOT NULL,
restaurantsreservations INT NOT NULL,
restaurantstableservice INT NOT NULL,
restaurantstakeout INT NOT NULL,
smoking INT NOT NULL,
wheelchairaccessible INT NOT NULL,
alcohol_false INT NOT NULL,
alcohol_beer_and_wine INT NOT NULL,
alcohol_full_bar INT NOT NULL,
byobcorkage_false INT NOT NULL,
byobcorkage_yes_corkage INT NOT NULL,
byobcorkage_yes_free INT NOT NULL,
noiselevel_average INT NOT NULL,
noiselevel_loud INT NOT NULL,
noiselevel_quiet INT NOT NULL,
noiselevel_very_loud INT NOT NULL,
restaurantsattire_casual INT NOT NULL,
restaurantsattire_dressy INT NOT NULL,
restaurantsattire_formal INT NOT NULL,
restaurantsattire_no_dress_code INT NOT NULL,
restaurantspricerange2_$10_and_under INT NOT NULL,
restaurantspricerange2_$11_to_30 INT NOT NULL,
restaurantspricerange2_$31_to_60 INT NOT NULL,
restaurantspricerange2_$61_and_over INT NOT NULL,
wifi_false INT NOT NULL,
wifi_free INT NOT NULL,
wifi_paid INT NOT NULL,
hipster INT NOT NULL,
classy INT NOT NULL,
intimate INT NOT NULL,
trendy INT NOT NULL,
casual INT NOT NULL,
touristy INT NOT NULL,
divey INT NOT NULL,
romantic INT NOT NULL,
upscale INT NOT NULL,
beer_bar INT NOT NULL,
thai INT NOT NULL,
food_stands INT NOT NULL,
salvadoran INT NOT NULL,
cuban INT NOT NULL,
donuts INT NOT NULL,
diners INT NOT NULL,
salad INT NOT NULL,
irish INT NOT NULL,
italian INT NOT NULL,
persian_iranian INT NOT NULL,
szechuan INT NOT NULL,
cafes INT NOT NULL,
vietnamese INT NOT NULL,
turkish INT NOT NULL,
tacos INT NOT NULL,
chicken_shop INT NOT NULL,
canadian_new INT NOT NULL,
belgian INT NOT NULL,
indian INT NOT NULL,
moroccan INT NOT NULL,
southern INT NOT NULL,
pan_asian INT NOT NULL,
tapas_small_plates INT NOT NULL,
desserts INT NOT NULL,
irish_pub INT NOT NULL,
local_flavor INT NOT NULL,
comfort_food INT NOT NULL,
ramen INT NOT NULL,
pizza INT NOT NULL,
bagels INT NOT NULL,
poke INT NOT NULL,
fish___chips INT NOT NULL,
peruvian INT NOT NULL,
waffles INT NOT NULL,
cantonese INT NOT NULL,
falafel INT NOT NULL,
american_traditional INT NOT NULL,
sandwiches INT NOT NULL,
french INT NOT NULL,
modern_european INT NOT NULL,
burgers INT NOT NULL,
dim_sum INT NOT NULL,
beer INT NOT NULL,
brasseries INT NOT NULL,
creperies INT NOT NULL,
tea_rooms INT NOT NULL,
jazz___blues INT NOT NULL,
brazilian INT NOT NULL,
street_vendors INT NOT NULL,
bistros INT NOT NULL,
taiwanese INT NOT NULL,
chicken_wings INT NOT NULL,
filipino INT NOT NULL,
fast_food INT NOT NULL,
vegan INT NOT NULL,
breakfast___brunch INT NOT NULL,
british INT NOT NULL,
asian_fusion INT NOT NULL,
colombian INT NOT NULL,
barbeque INT NOT NULL,
lounges INT NOT NULL,
cheesesteaks INT NOT NULL,
hungarian INT NOT NULL,
kebab INT NOT NULL,
arcades INT NOT NULL,
seafood INT NOT NULL,
bubble_tea INT NOT NULL,
juice_bars___smoothies INT NOT NULL,
sushi_bars INT NOT NULL,
cafeteria INT NOT NULL,
ice_cream___frozen_yogurt INT NOT NULL,
bakeries INT NOT NULL,
poutineries INT NOT NULL,
soup INT NOT NULL,
tapas_bars INT NOT NULL,
seafood_markets INT NOT NULL,
venezuelan INT NOT NULL,
internet_cafes INT NOT NULL,
acai_bowls INT NOT NULL,
themed_cafes INT NOT NULL,
hot_dogs INT NOT NULL,
himalayan_nepalese INT NOT NULL,
tex_mex INT NOT NULL,
american_new INT NOT NULL,
buffets INT NOT NULL,
coffee___tea INT NOT NULL,
delis INT NOT NULL,
wraps INT NOT NULL,
arabian INT NOT NULL,
steakhouses INT NOT NULL,
karaoke INT NOT NULL,
cajun_creole INT NOT NULL,
ethnic_food INT NOT NULL,
polish INT NOT NULL,
argentine INT NOT NULL,
latin_american INT NOT NULL,
caribbean INT NOT NULL,
halal INT NOT NULL,
hookah_bars INT NOT NULL,
do_it_yourself_food INT NOT NULL,
afghan INT NOT NULL,
noodles INT NOT NULL,
food INT NOT NULL,
chinese INT NOT NULL,
mediterranean INT NOT NULL,
new_mexican_cuisine INT NOT NULL,
vegetarian INT NOT NULL,
food_trucks INT NOT NULL,
ethiopian INT NOT NULL,
spanish INT NOT NULL,
german INT NOT NULL,
food_delivery_services INT NOT NULL,
african INT NOT NULL,
korean INT NOT NULL,
cocktail_bars INT NOT NULL,
dive_bars INT NOT NULL,
soul_food INT NOT NULL,
mongolian INT NOT NULL,
lebanese INT NOT NULL,
middle_eastern INT NOT NULL,
portuguese INT NOT NULL,
malaysian INT NOT NULL,
gastropubs INT NOT NULL,
japanese INT NOT NULL,
hot_pot INT NOT NULL,
hawaiian INT NOT NULL,
wine_bars INT NOT NULL,
greek INT NOT NULL,
sports_bars INT NOT NULL,
gluten_free INT NOT NULL,
pakistani INT NOT NULL,
mexican INT NOT NULL,
smokehouse INT NOT NULL,
hakka INT NOT NULL,
kosher INT NOT NULL,
caterers INT NOT NULL,

In [215]:
for i in new_attributes_table_2.drop(["business_id","name"], axis =1 ).columns:
    if len(new_attributes_table_2[i].value_counts().values) == 1:
        new_attributes_table_2.drop(i,axis = 1,inplace=True)

In [234]:
for i in new_attributes_table_2.drop(["business_id","name"], axis =1 ).columns:
    if new_attributes_table_2[i].value_counts().values[1] < 10:
        new_attributes_table_2.drop(i,axis = 1,inplace =True)

In [282]:
new_attributes_table_2.loc[new_attributes_table_2.brasseries == 1]

,business_id,name,byob,bikeparking,businessacceptsbitcoin,businessacceptscreditcards,byappointmentonly,caters,coatcheck,corkage,...,wine_bars,greek,sports_bars,gluten-free,pakistani,mexican,smokehouse,hakka,kosher,caterers
2470,ueq_FKGuXrhWg2hD-1rHtg,TPC Grille,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2941,4qG3Gh8QyugC1XvoTlmgcQ,Egg Works,0,1,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3434,ME6D5nLlfG0xZCtICOYDuw,Georges Brasserie,0,1,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
5656,8g8HWvgVT5M07yToLGWOcQ,Le Réservoir,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9292,VdfytVHrnTlOxWaNpDeVHg,Brisket Montreal,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10863,AcWAop2TvCRp-DhWl7qR6w,Le Pèlerin-Magellan,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11551,OJUTch0E4ZLtN8hQH2oFYg,Archibald Microbrasserie,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11940,K6XIGkyk7-fuOQtA8i7p6A,Mill Street Brew Pub,0,1,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
12527,QPq7OiHqyONN9relgqwFZA,Midway,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12911,NKTmsq4mfLn0uE6CMyINBA,Marcus Restaurant + Terrace,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
13322,LhwP2zI_KEueErtCB8zqrw,Café Souvenir,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14424,cF98fzqrMnikhXhuSz6ruQ,The Oak Barrel,0,1,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
16758,8NHV3DBvq9Q88ZtzdR6W2w,Le Saint-Bock,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17245,VxMtHC9OGNv6qw2XygRpng,La Brassée,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18114,TW6A7M0j0R9hp1zYpxz2FQ,District,0,1,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
20244,_SO-A-cRaCCjHxFNj8OJ7g,Bazille at Nordstrom,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21322,WDKTg468bkRPW0LqbAZfmg,Sugar Factory,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21843,qUdGBSFkiPhEL6I718y-Gg,Quai No.4,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22939,ZUPjGwDwoI41QyiSVYa8Fg,EtOH Brasserie,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31393,rTC7WSEvn5Bq5Bp2r3aVow,Rebel,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45559,j6__keNWOE8bVP_KVFs9cA,Bazille-Nordstrom,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
46854,QouAo7lqUhPtW7qZpkNS8g,La Cage,0,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
47479,X2bUZ2udFByvLlKs0FUMYw,Boswell,0,1,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
48383,xBxDMEkFK5GBhiy-8gGE9w,Brasserie T,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
52559,xgTQdHM3q2CZXQNnK5NPag,Brasserie Éléments,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
53557,cGR0XHCZ-tdXLd_REjXFsg,Furlough,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [244]:
new_attributes_table_2.drop(new_attributes_table_2.loc[new_attributes_table_2.grocery == 1].index,inplace = True)

In [290]:
new_attributes_table_2.drop("",axis = 1, inplace = True)

In [294]:
new_attributes_table_2.to_sql(
    "attributes_table_2",
    con = engine,
    index = False, 
    method = 'multi',
    chunksize = 10000,
    if_exists = "append"
)