## Simple Logistic Regression

In [1]:
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
yelp_data= pd.read_csv("../../Dataset/Cleaned/cleaned_table_2.csv")

In [3]:
yelp_data.head()

,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,business_id,...,wine_bars,greek,sports_bars,gluten_free,pakistani,mexican,smokehouse,hakka,kosher,caterers
0,1017 E Apache Blvd,Tempe,AZ,85281,33.414507,-111.923721,2.0,117,1,W7hCuNdn2gzehta6eSHzgQ,...,0,0,0,0,0,0,0,0,0,0
1,"1046 Regent Pkwy, Ste 107",Fort Mill,SC,29715,35.075476,-80.933904,4.0,267,1,PlP0c_u3g-3LiWHpb2XnOQ,...,0,0,0,0,0,0,0,0,0,0
2,3759 E Desert Inn Rd,Las Vegas,NV,89121,36.129178,-115.092483,5.0,222,1,AN0bWhisCf6LN9eHZ7DQ3w,...,0,0,0,0,0,0,0,0,0,0
3,"5115 Spring Mountain Rd, Ste 203",Las Vegas,NV,89146,36.125569,-115.210911,4.5,1142,1,AtD6B83S4Mbmq0t7iDnUVA,...,0,0,0,0,0,0,0,0,0,0
4,9311 Jw Clay Blvd,Charlotte,NC,28262,35.311397,-80.746334,3.5,124,0,ebwM2pckHieHvK6h1scuBw,...,0,0,0,0,0,0,0,0,0,0

In [4]:
yelp_data.columns

Index(['address', 'city', 'state', 'postal_code', 'latitude', 'longitude',
       'stars', 'review_count', 'is_open', 'business_id',
       ...
       'wine_bars', 'greek', 'sports_bars', 'gluten_free', 'pakistani',
       'mexican', 'smokehouse', 'hakka', 'kosher', 'caterers'],
      dtype='object', length=199)

In [5]:
# Creating a new empty column is_successful at the end of the Dataset
yelp_data["is_successful"] = ""
yelp_data

,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,business_id,...,greek,sports_bars,gluten_free,pakistani,mexican,smokehouse,hakka,kosher,caterers,is_successful
0,1017 E Apache Blvd,Tempe,AZ,85281,33.414507,-111.923721,2.0,117,1,W7hCuNdn2gzehta6eSHzgQ,...,0,0,0,0,0,0,0,0,0,
1,"1046 Regent Pkwy, Ste 107",Fort Mill,SC,29715,35.075476,-80.933904,4.0,267,1,PlP0c_u3g-3LiWHpb2XnOQ,...,0,0,0,0,0,0,0,0,0,
2,3759 E Desert Inn Rd,Las Vegas,NV,89121,36.129178,-115.092483,5.0,222,1,AN0bWhisCf6LN9eHZ7DQ3w,...,0,0,0,0,0,0,0,0,0,
3,"5115 Spring Mountain Rd, Ste 203",Las Vegas,NV,89146,36.125569,-115.210911,4.5,1142,1,AtD6B83S4Mbmq0t7iDnUVA,...,0,0,0,0,0,0,0,0,0,
4,9311 Jw Clay Blvd,Charlotte,NC,28262,35.311397,-80.746334,3.5,124,0,ebwM2pckHieHvK6h1scuBw,...,0,0,0,0,0,0,0,0,0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4113,300 Mt Lebanon Blvd,Pittsburgh,PA,15234,40.368716,-80.034629,3.5,84,1,vpwyL6NHm-pTWJ5IeJb9yw,...,0,0,0,0,1,0,0,0,0,
4114,"101 N 1st Ave, Ste 108",Phoenix,AZ,85004,33.449807,-112.074674,3.5,63,1,wTKMQD3nOwEKGZmtiiiGXA,...,0,0,0,0,0,0,0,0,0,
4115,1926 Sardis Rd N,Charlotte,NC,28270,35.140920,-80.732982,2.0,88,0,_JA3TLF5JJ95mthVwEdFuw,...,0,0,0,0,0,0,0,0,0,
4116,"835 Seven Hills Dr, Ste 190",Henderson,NV,89052,35.996722,-115.124645,3.5,60,0,7V82ANZ7_ARkA7o0pAMAlA,...,0,0,0,0,0,0,0,0,0,
4117,26410 Great Northern Shopping Ctr,North Olmsted,OH,44070,41.418407,-81.915597,3.5,120,1,8dK-8e006F_it5bNxTVlaQ,...,0,0,0,0,0,0,0,0,1,

In [6]:
## Criteria for is_successful
yelp_data.loc[yelp_data["stars"] >= 4.0, "is_successful"] = "yes"
yelp_data.loc[yelp_data["stars"] < 4.0, "is_successful"] = "no"

In [7]:
yelp_data.head()

,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,business_id,...,greek,sports_bars,gluten_free,pakistani,mexican,smokehouse,hakka,kosher,caterers,is_successful
0,1017 E Apache Blvd,Tempe,AZ,85281,33.414507,-111.923721,2.0,117,1,W7hCuNdn2gzehta6eSHzgQ,...,0,0,0,0,0,0,0,0,0,no
1,"1046 Regent Pkwy, Ste 107",Fort Mill,SC,29715,35.075476,-80.933904,4.0,267,1,PlP0c_u3g-3LiWHpb2XnOQ,...,0,0,0,0,0,0,0,0,0,yes
2,3759 E Desert Inn Rd,Las Vegas,NV,89121,36.129178,-115.092483,5.0,222,1,AN0bWhisCf6LN9eHZ7DQ3w,...,0,0,0,0,0,0,0,0,0,yes
3,"5115 Spring Mountain Rd, Ste 203",Las Vegas,NV,89146,36.125569,-115.210911,4.5,1142,1,AtD6B83S4Mbmq0t7iDnUVA,...,0,0,0,0,0,0,0,0,0,yes
4,9311 Jw Clay Blvd,Charlotte,NC,28262,35.311397,-80.746334,3.5,124,0,ebwM2pckHieHvK6h1scuBw,...,0,0,0,0,0,0,0,0,0,no

In [8]:
# LabelEncoder to turn the labels in the is_successful column to numbers.
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
model_df = yelp_data.copy()
model_df ['is_successful'] = le.fit_transform(model_df['is_successful'])
model_df.head()

,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,business_id,...,greek,sports_bars,gluten_free,pakistani,mexican,smokehouse,hakka,kosher,caterers,is_successful
0,1017 E Apache Blvd,Tempe,AZ,85281,33.414507,-111.923721,2.0,117,1,W7hCuNdn2gzehta6eSHzgQ,...,0,0,0,0,0,0,0,0,0,0
1,"1046 Regent Pkwy, Ste 107",Fort Mill,SC,29715,35.075476,-80.933904,4.0,267,1,PlP0c_u3g-3LiWHpb2XnOQ,...,0,0,0,0,0,0,0,0,0,1
2,3759 E Desert Inn Rd,Las Vegas,NV,89121,36.129178,-115.092483,5.0,222,1,AN0bWhisCf6LN9eHZ7DQ3w,...,0,0,0,0,0,0,0,0,0,1
3,"5115 Spring Mountain Rd, Ste 203",Las Vegas,NV,89146,36.125569,-115.210911,4.5,1142,1,AtD6B83S4Mbmq0t7iDnUVA,...,0,0,0,0,0,0,0,0,0,1
4,9311 Jw Clay Blvd,Charlotte,NC,28262,35.311397,-80.746334,3.5,124,0,ebwM2pckHieHvK6h1scuBw,...,0,0,0,0,0,0,0,0,0,0

In [9]:
# Excluding unnecessary columns in the model
x_cols = [i for i in model_df.columns if i not in ('address', 'city', 'state',
                                             'postal_code', 'latitude', 'longitude', 'business_id',
                                             'name','is_successful')]

In [10]:
X = model_df[x_cols]
y = model_df['is_successful']

In [11]:
# Splitting our data into testing and training sets.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=1, stratify=y)

In [12]:
# Number of rows and columns in X_train.shape
X_train.shape

(3088, 191)

In [13]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs', max_iter=2000,random_state=1)
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=2000, random_state=1)

In [14]:
# Creating predictions for y-values using the X_test set
y_pred = classifier.predict(X_test)
pd.DataFrame({"Prediction": y_pred, "Actual": y_test})

      Prediction  Actual
2472           1       1
1394           0       0
2857           1       1
2023           0       0
2677           0       0
...          ...     ...
2451           0       0
552            0       0
681            1       1
2021           1       1
3356           1       1

[1030 rows x 2 columns]

In [15]:
# Balanced Accuracy Score
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

1.0